site_name: Multiauth
site_description: The ultimate Python Authentication toolkit
strict: true

theme:
  name: "material"
  custom_dir: docs/overrides
  favicon: assets/images/favicon.png
  logo: assets/images/favicon.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/lightbulb-outline
        name: "Switch to dark mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/lightbulb
        name: "Switch to light mode"
  features:
    - content.tabs.link

    - content.code.annotate
    - content.code.copy
    - content.code.select

    - content.action.edit
    - search.suggest
    - search.highlight

    - navigation.top
    - navigation.footer
    - navigation.tracking
    - navigation.sections
    - navigation.path

    - toc.follow

  icon:
    repo: fontawesome/brands/github
  copyright: Copyright &copy; 2022 - 2024 Escape

nav:
  - Getting Started:
      - Welcome to Multiauth: "index.md"
      - Installation: "installation.md"
      - What is Multiauth: "about.md"
      - Migration from V2: "migrating.md"
  - Concepts:
      - Authentication: "concepts/authentication.md"
      - Procedures: "concepts/procedures.md"
      - Variables: "concepts/variables.md"
      - Users: "concepts/users.md"
      - Presets: "concepts/presets.md"
  - Your first procedure:
      - Introduction: "first-procedure/introduction.md"
      - Creating a procedure: "first-procedure/first-procedure.md"
      - Declaring variables: "first-procedure/declaring-variables.md"
      - Adding a user: "first-procedure/adding-user.md"
      - Authenticating: "first-procedure/authenticating.md"
  - API Reference:
      - CLI interface: "reference/cli.md"
      - Programmatic interface: "reference/programmatic.md"
      - Configuration: "reference/configuration.md"
      - Reference: reference/reference.md
  - Help: "help.md"
  - Versioning: "versioning.md"
  - Changelog: "changelog.md"
  - Contributing: "contributing.md"

repo_name: Escape-Technologies/py-multiauth
repo_url: https://github.com/Escape-Technologies/py-multiauth
edit_uri: edit/main/revamp/docs/

# https://www.mkdocs.org/user-guide/configuration/#validation
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

watch:
  - docs

plugins:
  - search

markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      combine_header_slug: true
      alternate_style: true
  - toc:
      permalink: true
      title: On this page
  - pymdownx.snippets
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
