name: CI
on:
  push:
  pull_request:
    types: [opened, reopened]

env:
  MODULE_NAME: multiauth
  MIN_TEST_COV: 30

jobs:
  CI:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12.1"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install poetry
      - name: Setup poetry
        run: |
          poetry config virtualenvs.in-project true
          poetry install
      - name: Run lint
        if: always()
        run: |
          source .venv/bin/activate
          ruff -V
          mypy -V
          black --version
          yamllint --version
          black $MODULE_NAME scripts
          ruff check $MODULE_NAME scripts
          mypy $MODULE_NAME scripts
          yamllint $MODULE_NAME scripts -s
      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest -V
          pytest --cov=$MODULE_NAME --cov-report=xml --cov-fail-under=$MIN_TEST_COV tests/unit/
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
